version: '3.5'

services:
  olahds_user_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olahds_user_frontend
    networks:
      - olahd
    ports:
      - "8090:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olahds_user_frontend.entrypoints=web"
      - "traefik.http.routers.olahds_user_frontend.rule=PathPrefix(`/`)"

networks:
  olahd:
    external: true
