version: '3.2'

services:
  olahds_user_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olahds_user_frontend
    networks:
      - olahd
    ports:
      - "8090:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olahds_user_frontend.entrypoints=http"
      - "traefik.http.routers.olahds_user_frontend.rule=PathPrefix(`/home`)"
      - "traefik.http.routers.olahds_user_frontend.middlewares=stripprefix_home"
      - "traefik.http.middlewares.stripprefix_home.stripprefix.prefixes=/home"

networks:
  olahd:
    external: true
