# This workflow deploys the olahd-user-frontend on he devserver. Deployment is done with an existing
# script on the server. This script updates the sources, shuts down user-frontend docker-containers
# and finally builds and starts it again.

name: Deploy olahd-user-frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: copy key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
        env:
          SSH_KEY: ${{ secrets.OLAHD_SSH_KEY }}

      - name: run deploy script
        run: ssh $SSH_USER@$SSH_HOST -o StrictHostKeyChecking=no -i ~/.ssh/key /home/$SSH_USER/start-olahd-docker.sh uf
        env:
          SSH_USER: ${{ secrets.OLAHD_SSH_USER }}
          SSH_HOST: ${{ secrets.OLAHD_SSH_HOST }}
